## Task 1: Reverse a string

**Prompt:** Write a Python program to reverse a string.

In [1]:
text = "interview"
print("Original:", text)
print("Reversed:", text[::-1])

Original: interview
Reversed: weivretni

## Task 2: Check palindrome

**Prompt:** Write a program to check whether a string is a palindrome, ignoring letter case.

In [2]:
text = "Madam"
normalized = text.lower()
print("Is palindrome:", normalized == normalized[::-1])

Is palindrome: True

## Task 3: Count vowels

**Prompt:** Count the vowels in a string.

In [3]:
text = "Python Programming"
vowels = set("aeiou")
count = sum(1 for ch in text.lower() if ch in vowels)
print("Vowel count:", count)

Vowel count: 4

## Task 4: Character frequency

**Prompt:** Count how many times each character appears in a string.

In [4]:
text = "banana"
frequency = {}
for ch in text:
    frequency[ch] = frequency.get(ch, 0) + 1
print(frequency)

{'b': 1, 'a': 3, 'n': 2}

## Task 5: Factorial

**Prompt:** Calculate the factorial of a non-negative integer using a loop.

In [5]:
n = 5
factorial = 1
for number in range(1, n + 1):
    factorial *= number
print(f"{n}! =", factorial)

5! = 120

## Task 6: Prime number

**Prompt:** Check whether a number is prime.

In [6]:
n = 29
is_prime = n >= 2
for divisor in range(2, int(n ** 0.5) + 1):
    if n % divisor == 0:
        is_prime = False
        break
print(f"{n} is prime:", is_prime)

29 is prime: True

## Task 7: Second-largest distinct number

**Prompt:** Find the second-largest distinct element in a list, handling duplicates.

In [7]:
numbers = [10, 20, 4, 20, 15]
unique_numbers = sorted(set(numbers))
if len(unique_numbers) >= 2:
    print("Second-largest:", unique_numbers[-2])
else:
    print("No second-largest distinct element")

Second-largest: 15

## Task 8: Remove duplicates from a list

**Prompt:** Remove duplicate values from a list while preserving the original order.

In [8]:
numbers = [3, 1, 3, 2, 1, 4]
unique_numbers = list(dict.fromkeys(numbers))
print(unique_numbers)

[3, 1, 2, 4]

## Task 9: Find common elements

**Prompt:** Find the common elements between two lists without repeating results.

In [9]:
a = [1, 2, 2, 3, 4]
b = [2, 4, 4, 5]
common = sorted(set(a) & set(b))
print("Common elements:", common)

Common elements: [2, 4]

## Task 10: Rotate a list right

**Prompt:** Rotate a list to the right by k positions.

In [10]:
numbers = [1, 2, 3, 4, 5]
k = 2
k %= len(numbers)
rotated = numbers[-k:] + numbers[:-k] if k else numbers[:]
print(rotated)

[4, 5, 1, 2, 3]

## Task 11: Merge two dictionaries

**Prompt:** Merge two dictionaries; if a key occurs in both, the second dictionary's value should win.

In [11]:
first = {"a": 1, "b": 2}
second = {"b": 20, "c": 3}
merged = {**first, **second}
print(merged)

{'a': 1, 'b': 20, 'c': 3}

## Task 12: Word frequency

**Prompt:** Count the frequency of each word in a sentence, ignoring case.

In [12]:
sentence = "Python is easy and Python is powerful"
frequency = {}
for word in sentence.lower().split():
    frequency[word] = frequency.get(word, 0) + 1
print(frequency)

{'python': 2, 'is': 2, 'easy': 1, 'and': 1, 'powerful': 1}

## Task 13: Set operations

**Prompt:** Display the union and intersection of two sets.

In [13]:
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}
print("Union:", sorted(a | b))
print("Intersection:", sorted(a & b))

Union: [1, 2, 3, 4, 5, 6]
Intersection: [3, 4]

## Task 14: Sort dictionary by value

**Prompt:** Sort a dictionary by its values in ascending order.

In [14]:
scores = {"Ravi": 82, "Anu": 95, "Kiran": 76}
sorted_scores = dict(sorted(scores.items(), key=lambda item: item[1]))
print(sorted_scores)

{'Kiran': 76, 'Ravi': 82, 'Anu': 95}

## Task 15: NumPy array statistics

**Prompt:** Create a NumPy array and display its mean, minimum, maximum, and standard deviation.

In [15]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Standard deviation:", round(np.std(arr), 2))

Array: [10 20 30 40 50]
Mean: 30.0
Minimum: 10
Maximum: 50
Standard deviation: 14.14

## Task 16: NumPy reshape

**Prompt:** Create an array containing numbers 1 through 6 and reshape it into 2 rows and 3 columns.

In [16]:
import numpy as np

arr = np.arange(1, 7).reshape(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]

## Task 17: NumPy filtering

**Prompt:** Use NumPy to select values greater than 25 from an array.

In [17]:
import numpy as np

arr = np.array([10, 25, 30, 15, 40])
print(arr[arr > 25])

[30 40]

## Task 18: Pandas DataFrame

**Prompt:** Create a Pandas DataFrame for three students and display it.

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Anu", "Ravi", "Kiran"],
    "Marks": [88, 76, 92]
})
print(df.to_string(index=False))

 Name  Marks
  Anu     88
 Ravi     76
Kiran     92

## Task 19: Pandas missing values

**Prompt:** Fill missing values in a Pandas column with the column's mean.

In [19]:
import pandas as pd

df = pd.DataFrame({"Marks": [80.0, None, 90.0, 70.0]})
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df.to_string(index=False))

 Marks
  80.0
  80.0
  90.0
  70.0

## Task 20: Pandas filter and sort

**Prompt:** Filter students with marks of at least 80 and sort them by marks in descending order.

In [20]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Anu", "Ravi", "Kiran", "Meena"],
    "Marks": [88, 76, 92, 80]
})
result = df[df["Marks"] >= 80].sort_values("Marks", ascending=False)
print(result.to_string(index=False))

 Name  Marks
Kiran     92
  Anu     88
Meena     80

## Task 21: Pandas groupby

**Prompt:** Group sales by category and calculate total sales for each category.

In [21]:
import pandas as pd

df = pd.DataFrame({
    "Category": ["Food", "Books", "Food", "Books", "Clothes"],
    "Sales": [200, 150, 300, 100, 250]
})
print(df.groupby("Category", as_index=False)["Sales"].sum().to_string(index=False))

Category  Sales
   Books    250
 Clothes    250
    Food    500

## Task 22: Pandas remove duplicates

**Prompt:** Remove duplicate rows from a Pandas DataFrame.

In [22]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Anu", "Ravi", "Anu"],
    "City": ["Chirala", "Guntur", "Chirala"]
})
print(df.drop_duplicates().to_string(index=False))

Name    City
 Anu Chirala
Ravi  Guntur

# SQL Interview Tasks

SQL examples run inside an in-memory SQLite database. The setup cell creates sample `Employees` and `Departments` tables. Run tasks in order because later tasks use the same database.

## SQL setup

**Prompt:** Create sample employee and department tables and insert data for interview practice.

In [23]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")
cur = conn.cursor()

cur.executescript("""
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Departments;

CREATE TABLE Departments (
    department_id INTEGER PRIMARY KEY,
    department_name TEXT NOT NULL
);

CREATE TABLE Employees (
    employee_id INTEGER PRIMARY KEY,
    employee_name TEXT NOT NULL,
    department_id INTEGER,
    salary INTEGER,
    manager_id INTEGER,
    FOREIGN KEY (department_id) REFERENCES Departments(department_id)
);

INSERT INTO Departments VALUES
(1, 'Engineering'), (2, 'HR'), (3, 'Sales');

INSERT INTO Employees VALUES
(101, 'Anu', 1, 60000, NULL),
(102, 'Ravi', 1, 75000, 101),
(103, 'Kiran', 2, 50000, 101),
(104, 'Meena', 3, 55000, 102),
(105, 'Arjun', 1, 75000, 102),
(106, 'Divya', 2, 45000, 103);
""")
conn.commit()

def show_query(query):
    display(pd.read_sql_query(query, conn))

print("Tables created and sample data inserted.")
display(pd.read_sql_query("SELECT * FROM Employees ORDER BY employee_id", conn))

Tables created and sample data inserted.

   employee_id employee_name  department_id  salary  manager_id
0          101           Anu              1   60000         NaN
1          102          Ravi              1   75000       101.0
2          103         Kiran              2   50000       101.0
3          104         Meena              3   55000       102.0
4          105         Arjun              1   75000       102.0
5          106         Divya              2   45000       103.0

## Task 23: SELECT and WHERE

**Prompt:** Select employees whose salary is greater than 55000.

In [24]:
show_query("""
SELECT employee_name, salary
FROM Employees
WHERE salary > 55000
ORDER BY salary DESC;
""")

  employee_name  salary
0          Ravi   75000
1         Arjun   75000
2           Anu   60000

## Task 24: ORDER BY and LIMIT

**Prompt:** Display the three highest-paid employees.

In [25]:
show_query("""
SELECT employee_name, salary
FROM Employees
ORDER BY salary DESC
LIMIT 3;
""")

  employee_name  salary
0          Ravi   75000
1         Arjun   75000
2           Anu   60000

## Task 25: Aggregate functions

**Prompt:** Find the number of employees, average salary, minimum salary, and maximum salary.

In [26]:
show_query("""
SELECT COUNT(*) AS employee_count,
       ROUND(AVG(salary), 2) AS average_salary,
       MIN(salary) AS minimum_salary,
       MAX(salary) AS maximum_salary
FROM Employees;
""")

   employee_count  average_salary  minimum_salary  maximum_salary
0               6         60000.0           45000           75000

## Task 26: GROUP BY and HAVING

**Prompt:** Show departments whose average salary is greater than 55000.

In [27]:
show_query("""
SELECT d.department_name, ROUND(AVG(e.salary), 2) AS average_salary
FROM Employees e
JOIN Departments d ON e.department_id = d.department_id
GROUP BY d.department_name
HAVING AVG(e.salary) > 55000;
""")

  department_name  average_salary
0     Engineering         70000.0

## Task 27: INNER JOIN

**Prompt:** Display each employee with their department name using an INNER JOIN.

In [28]:
show_query("""
SELECT e.employee_name, d.department_name
FROM Employees e
INNER JOIN Departments d ON e.department_id = d.department_id
ORDER BY e.employee_id;
""")

  employee_name department_name
0           Anu     Engineering
1          Ravi     Engineering
2         Kiran              HR
3         Meena           Sales
4         Arjun     Engineering
5         Divya              HR

## Task 28: LEFT JOIN

**Prompt:** Display all departments and any employees in each department, including departments with no employees.

In [29]:
show_query("""
SELECT d.department_name, e.employee_name
FROM Departments d
LEFT JOIN Employees e ON d.department_id = e.department_id
ORDER BY d.department_id, e.employee_id;
""")

  department_name employee_name
0     Engineering           Anu
1     Engineering          Ravi
2     Engineering         Arjun
3              HR         Kiran
4              HR         Divya
5           Sales         Meena

## Task 29: UNION

**Prompt:** Combine employee names with department names using UNION, removing duplicates.

In [30]:
show_query("""
SELECT employee_name AS name FROM Employees
UNION
SELECT department_name AS name FROM Departments
ORDER BY name;
""")

          name
0          Anu
1        Arjun
2        Divya
3  Engineering
4           HR
5        Kiran
6        Meena
7         Ravi
8        Sales

## Task 30: Find duplicate values

**Prompt:** Find salary values shared by more than one employee.

In [31]:
show_query("""
SELECT salary, COUNT(*) AS number_of_employees
FROM Employees
GROUP BY salary
HAVING COUNT(*) > 1;
""")

   salary  number_of_employees
0   75000                    2

## Task 31: Subquery

**Prompt:** Find employees earning more than the overall average salary.

In [32]:
show_query("""
SELECT employee_name, salary
FROM Employees
WHERE salary > (SELECT AVG(salary) FROM Employees)
ORDER BY salary DESC;
""")

  employee_name  salary
0          Ravi   75000
1         Arjun   75000

## Task 32: LEAD and LAG window functions

**Prompt:** Show each employee's salary along with the previous and next salary when employees are ordered by employee ID.

In [33]:
show_query("""
SELECT employee_name, salary,
       LAG(salary) OVER (ORDER BY employee_id) AS previous_salary,
       LEAD(salary) OVER (ORDER BY employee_id) AS next_salary
FROM Employees
ORDER BY employee_id;
""")

  employee_name  salary  previous_salary  next_salary
0           Anu   60000              NaN      75000.0
1          Ravi   75000          60000.0      50000.0
2         Kiran   50000          75000.0      55000.0
3         Meena   55000          50000.0      75000.0
4         Arjun   75000          55000.0      45000.0
5         Divya   45000          75000.0          NaN

## Task 33: UPDATE

**Prompt:** Increase Ravi's salary to 80000 and display the updated row.

In [34]:
cur.execute("UPDATE Employees SET salary = 80000 WHERE employee_name = 'Ravi'")
conn.commit()
show_query("SELECT employee_name, salary FROM Employees WHERE employee_name = 'Ravi'")

  employee_name  salary
0          Ravi   80000

## Task 34: DELETE

**Prompt:** Delete the employee whose ID is 106, then display the remaining number of employees.

In [35]:
cur.execute("DELETE FROM Employees WHERE employee_id = 106")
conn.commit()
show_query("SELECT COUNT(*) AS remaining_employees FROM Employees")

   remaining_employees
0                    5

## Task 35: TRUNCATE equivalent in SQLite

**Prompt:** Empty a practice table. SQLite does not support TRUNCATE TABLE, so use DELETE without a WHERE clause.

In [36]:
cur.executescript("""
DROP TABLE IF EXISTS TempRecords;
CREATE TABLE TempRecords (record_id INTEGER, label TEXT);
INSERT INTO TempRecords VALUES (1, 'A'), (2, 'B'), (3, 'C');
DELETE FROM TempRecords;
""")
show_query("SELECT COUNT(*) AS rows_after_emptying FROM TempRecords")

   rows_after_emptying
0                    0

## Task 36: CREATE TABLE and INSERT

**Prompt:** Create a Courses table, insert two records, and display them.

In [37]:
cur.executescript("""
DROP TABLE IF EXISTS Courses;
CREATE TABLE Courses (
    course_id INTEGER PRIMARY KEY,
    course_name TEXT NOT NULL,
    duration_weeks INTEGER
);
INSERT INTO Courses VALUES (1, 'Python', 6), (2, 'SQL', 4);
""")
show_query("SELECT * FROM Courses ORDER BY course_id")

   course_id course_name  duration_weeks
0          1      Python               6
1          2         SQL               4

## Task 37: CASE expression

**Prompt:** Label employees as High salary if salary is at least 70000, otherwise Standard salary.

In [38]:
show_query("""
SELECT employee_name, salary,
       CASE WHEN salary >= 70000 THEN 'High salary'
            ELSE 'Standard salary'
       END AS salary_band
FROM Employees
ORDER BY employee_id;
""")

  employee_name  salary      salary_band
0           Anu   60000  Standard salary
1          Ravi   80000      High salary
2         Kiran   50000  Standard salary
3         Meena   55000  Standard salary
4         Arjun   75000      High salary